name: CI - tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10']

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python ${{ matriz.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matriz.python-version }}
          cache: 'pip'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Executar testes com pytest
        run: |
          pytest test/
